version: AE
description: autoencoder
# filepath
root_dir: ../../data/dcase2022dataset
train_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/train
  - ../../data/dcase2022dataset/dev_data/slider/train
  - ../../data/dcase2022dataset/dev_data/valve/train
  - ../../data/dcase2022dataset/dev_data/ToyCar/train
  - ../../data/dcase2022dataset/dev_data/ToyTrain/train
  - ../../data/dcase2022dataset/dev_data/bearing/train
  - ../../data/dcase2022dataset/dev_data/gearbox/train
add_train_dirs:
  - ../../data/dcase2022dataset/eval_data/fan/train
  - ../../data/dcase2022dataset/eval_data/slider/train
  - ../../data/dcase2022dataset/eval_data/valve/train
  - ../../data/dcase2022dataset/eval_data/ToyCar/train
  - ../../data/dcase2022dataset/eval_data/ToyTrain/train
  - ../../data/dcase2022dataset/eval_data/bearing/train
  - ../../data/dcase2022dataset/eval_data/gearbox/train
valid_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/test
  - ../../data/dcase2022dataset/dev_data/slider/test
  - ../../data/dcase2022dataset/dev_data/valve/test
  - ../../data/dcase2022dataset/dev_data/ToyCar/test
  - ../../data/dcase2022dataset/dev_data/ToyTrain/test
  - ../../data/dcase2022dataset/dev_data/bearing/test
  - ../../data/dcase2022dataset/dev_data/gearbox/test
test_dirs:
  - ../../data/eval_dataset/fan/test
  - ../../data/eval_dataset/pump/test
  - ../../data/eval_dataset/slider/test
  - ../../data/eval_dataset/valve/test
  - ../../data/eval_dataset/ToyCar/test
  - ../../data/eval_dataset/ToyConveyor/test
# audio
sr: 16000
n_frames: 5
n_hop_frames: 1
n_mels: 128
# train
seed: 526
epochs: 100
batch_size: 16
num_workers: 32
lr: 0.0001
device_ids:
  - 3
start_scheduler_epoch: 20
valid_every_epochs: 2
early_stop_epochs: -1
test: False