version: dcase2022task2
description: STgramMFN, Sample imbalance
# filepath
root_dir: ../../data/dcase2022dataset
train_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/train
  - ../../data/dcase2022dataset/dev_data/slider/train
  - ../../data/dcase2022dataset/dev_data/valve/train
  - ../../data/dcase2022dataset/dev_data/ToyCar/train
  - ../../data/dcase2022dataset/dev_data/ToyTrain/train
  - ../../data/dcase2022dataset/dev_data/bearing/train
  - ../../data/dcase2022dataset/dev_data/gearbox/train
  - ../../data/dcase2022dataset/eval_data/fan/train
  - ../../data/dcase2022dataset/eval_data/slider/train
  - ../../data/dcase2022dataset/eval_data/valve/train
  - ../../data/dcase2022dataset/eval_data/ToyCar/train
  - ../../data/dcase2022dataset/eval_data/ToyTrain/train
  - ../../data/dcase2022dataset/eval_data/bearing/train
  - ../../data/dcase2022dataset/eval_data/gearbox/train
valid_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/test
  - ../../data/dcase2022dataset/dev_data/slider/test
  - ../../data/dcase2022dataset/dev_data/valve/test
  - ../../data/dcase2022dataset/dev_data/ToyCar/test
  - ../../data/dcase2022dataset/dev_data/ToyTrain/test
  - ../../data/dcase2022dataset/dev_data/bearing/test
  - ../../data/dcase2022dataset/dev_data/gearbox/test
test_dirs:
  - ../../data/eval_dataset/fan/test
  - ../../data/eval_dataset/bearing/test
  - ../../data/eval_dataset/slider/test
  - ../../data/eval_dataset/valve/test
  - ../../data/eval_dataset/ToyCar/test
  - ../../data/eval_dataset/ToyTrain/test
  - ../../data/eval_dataset/gearbox/test
# audio
sr: 16000
mean: False
std: False
# train
seed: 42
epochs: 50
# 154
batch_size: 154
num_workers: 32
lr: 1e-4
device_ids:
#  - 2
#  - 4
#  - 5
  - 0
  - 1
start_scheduler_epoch: 20
valid_every_epochs: 2
early_stop_epochs: -1
test: False

# net
arcface: True
m: 0.5
s: 5
sub: 1