version: dcase2022task2
description: STgramMFN, Sample imbalance
# filepath
root_dir: ../../data/dcase2022dataset
train_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/train
  - ../../data/dcase2022dataset/dev_data/slider/train
  - ../../data/dcase2022dataset/dev_data/valve/train
  - ../../data/dcase2022dataset/dev_data/ToyCar/train
  - ../../data/dcase2022dataset/dev_data/ToyTrain/train
  - ../../data/dcase2022dataset/dev_data/bearing/train
  - ../../data/dcase2022dataset/dev_data/gearbox/train
  - ../../data/dcase2022dataset/eval_data/fan/train
  - ../../data/dcase2022dataset/eval_data/slider/train
  - ../../data/dcase2022dataset/eval_data/valve/train
  - ../../data/dcase2022dataset/eval_data/ToyCar/train
  - ../../data/dcase2022dataset/eval_data/ToyTrain/train
  - ../../data/dcase2022dataset/eval_data/bearing/train
  - ../../data/dcase2022dataset/eval_data/gearbox/train
valid_dirs:
  - ../../data/dcase2022dataset/dev_data/fan/test
  - ../../data/dcase2022dataset/dev_data/slider/test
  - ../../data/dcase2022dataset/dev_data/valve/test
  - ../../data/dcase2022dataset/dev_data/ToyCar/test
  - ../../data/dcase2022dataset/dev_data/ToyTrain/test
  - ../../data/dcase2022dataset/dev_data/bearing/test
  - ../../data/dcase2022dataset/dev_data/gearbox/test
test_dirs:
  - ../../data/eval_dataset/fan/test
  - ../../data/eval_dataset/bearing/test
  - ../../data/eval_dataset/slider/test
  - ../../data/eval_dataset/valve/test
  - ../../data/eval_dataset/ToyCar/test
  - ../../data/eval_dataset/ToyTrain/test
  - ../../data/eval_dataset/gearbox/test
# audio
sr: 16000
mean: False
std: False
# train
seed: 42
epochs: 300
batch_size: 154
num_workers: 32
lr: 1e-4
device_ids:
#  - 2
#  - 4
#  - 5
  - 0
  - 1
start_scheduler_epoch: 20
valid_every_epochs: 2
early_stop_epochs: -1
test: False

# net
arcface: True
m: 0.5
s: 5
sub: 1

decision_threshold: 0.9
# gwrp decay
#gwrp_decays: {ToyCar: 0.99,
#              ToyTrain: 0.81,
#              bearing: 1.00,
#              fan: 1.00,
#              gearbox: 0.99,
#              slider: 0.88,
#              valve: 0.45}
#gmm_ns: {ToyCar: 2,
#         ToyTrain: 2,
#         bearing: 2,
#         fan: 2,
#         gearbox: 2,
#         slider: 1,
#         valve: 2}


# GMM mean center 2,2,2,2,2,2,1
# GMM max center 2,2,2,2,2,1,2
smotes:
  ToyCar: True
  ToyTrain: False
  bearing: False
  fan: False
  gearbox: True
  slider: True
  valve: True
gwrp_decays: {ToyCar: 1.00,
              ToyTrain: 0.81,
              bearing: 1.00,
              fan: 1.00,
              gearbox: 0.98,
              slider: 0.90,
              valve: 0.50}
gmm_ns: {ToyCar: 1,
         ToyTrain: 2,
         bearing: 2,
         fan: 2,
         gearbox: 2,
         slider: 1,
         valve: 2}